name: Release

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  semver_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Calculate Semantic Version Bump
        id: tagger
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          noVersionBumpBehavior: current

      - name: Create GitHub Release
        if: ${{ steps.tagger.outputs.next != steps.tagger.outputs.current }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tagger.outputs.next }}
          generate_release_notes: true
